# Generic Settings
version: '{build}-{branch}'

matrix:
  fast_finish: true

# Build Image & Environment
platform: x64

# Build Tags only
skip_non_tags: true

image:
  - Visual Studio 2017

environment:
  CMAKE_SYSTEM_VERSION: 10.0.17134.0
  CMAKE_GENERATOR_32: "Visual Studio 15 2017"
  CMAKE_GENERATOR_64: "Visual Studio 15 2017 Win64"
  PACKAGE_PREFIX: obs-stream-effects
  INNOSETUP_URL: http://www.jrsoftware.org/download.php/is.exe
  CURL_VERSION: 7.39.0

# Resource Cache
cache:
  - inno.exe
  - build/32/libobs-download
  - build/32/libobs-src
  - build/64/libobs-download
  - build/64/libobs-src

# Repository Settings
branches:
  except:
    - /i18n_.*/
    - /i18n_master/
    - i18n_master
    - /l10n_.*/
    - /l10n_master/
    - l10n_master

# Building  
install:
- cmd: ci/appveyor-install.bat

build_script:
- cmd: node ci/builder.js

after_build:
- cmd: node ci/packager.js
- cmd: ci/appveyor-package.bat

# Testing
test: off

# Artifacts
artifacts:
  - path: build/obs-stream-effects-*.zip
  - path: build/obs-stream-effects-*.7z
  - path: build/obs-stream-effects-*.exe

# Deploying
deploy:
  - provider: GitHub
    auth_token:
      secure: QwBI/KNma7xeTcwQUGpTNSFaZU13Qv9UpiqUKHndJgAsh3aoRM8jnGUvCcg8aQIO
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

# Notifications
notifications:
  - provider: Webhook
    url: 
      secure: PTtt5ALhmK0q42jYyx4/Qa1Uf18+gLMXKGdzJjDISJt8IE/K0Zyp58UYmDDbbyLp4pBRf/Ylj8rn/zYL/mqBoDVRIH5zasPqIvBD0ZhtvNjTOxQ3QoRkAmxgpWeMowm3A3I1rLizA2H4EctPpoAJGrvQ1G2HEYn9tVsGYeetFTo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
    body: >-
      {
        "content": "**Build {{status}}**: [{{commitId}}] {{commitMessage}}\nBy {{commitAuthor}} on {{commitDate}}\n{{buildUrl}}"
      }
